### ISSUE TITLE
ARR ideas list

### ISSUE THREAD

**Issue by arr28** [SanchoGGP/ggp-base#12]
A list of ideas for improvement (in approximate order of interest within each category).
#### Playing strength
- [x] ~~#9 Weak GDL isomorphism test as a precursor to...~~
- [ ] ...state saving and reloading.
- [x] ~~#19 Dynamic adjustment of rollout count based on blocking time~~
- [x] #92 Check that Sancho can win all published single-player games
- [ ] Heuristics
  - [x] ~~#29 Add mobility heuristic (and learn weight), probably needed to fix #13.~~
  - [ ] History heuristic (needs state saving & loading)
  - [ ] #25 Goal heuristic
  - [ ] Think about the heuristic horizon effect
- [ ] Identify games which are provably 2-player win/draw/loss (100/50/0) games.
- [x] #44 Latch identification
- [x] ~~#26 Factoring~~
- [ ] #47 Increase exploration bias for unpredictable opponents
#### Debugging
- [x] ~~#8 Debug line of thought.~~
- [x] ~~#62 Log & graph statistics (a la GreenShell).~~
#### Reliability
- [ ] #16 Live network latency modelling.
