### ISSUE TITLE
ARR 2014 Task list

### ISSUE THREAD

**Issue by arr28** [SanchoGGP/ggp-base#155]
- [x] Merge 2014Candidates branch
- [x] Review IrrelevantFactors branch
- [x] Test corrected version of Arithmetic (see #157)
- [x] Test other puzzles & pseudo-puzzles (see #92)
- [x] Leave active on Tiltyard
- [x] Identify cause of excessive allocation in Duikoshi (split out to #160)
